---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config-server
  namespace: app
type: Opaque
stringData:
  token: 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
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: app
  labels:
    deploy: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: alberth1414/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: GIT_URI
              value: https://github.com/Garita-Sofware/Config
            - name: GIT_USERNAME
              value: alberthgarita
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-config-server
                  key: token
            - name: GIT_BRANCH
              value: main
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: app
spec:
  selector:
    app: configserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
